config/routes.rb
FbConnect::Application.routes.draw do
  resource :session,   only: :destroy
  resource :dashboard, only: :show
  resource :facebook do
    member do
      get :authorize
      get :callback
    end
  end

  root 'top#show'
end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :require_authentication

  def show
  end
end

app/controllers/facebooks_controller.rb
class FacebooksController < ApplicationController
  before_filter :require_anonymous_access

  def authorize
    redirect_to provider.authorization_uri
  end

  def callback
    provider.authorization_code = params[:code]
    fb_token = provider.access_token! :body
    fb_profile = FbGraph::User.me(fb_token).fetch(
      fields: [:id, :name, :username]
    )

    current_account = Account.where(
      fb_uid: fb_profile.identifier
    ).first_or_create
    authenticate current_account

    redirect_to dashboard_url
  end

  private

  def provider
    @provider ||= Rack::OAuth2::Client.new(
      identifier: '130982493738728',
      secret: 'ba04b7cd41dc814c83b4ae568c0c8e74',
      authorization_endpoint: 'https://www.facebook.com/dialog/oauth',
      token_endpoint: 'https://graph.facebook.com/oauth/access_token',
      redirect_uri: callback_facebook_url
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_authentication

  def destroy
    unauthenticate!
    redirect_to root_url
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_filter :require_anonymous_access

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Authentication::Helper
end

app/views/dashboards/show.html.erb
<article>
  <h2>Logged-in as FB User #<%= current_account.fb_uid %></h2>
  <%= image_tag FbGraph::User.new(current_account.fb_uid).picture(type: :large) %>
</article>

app/views/layouts/_footer.html.erb
<footer class="page_footer">
  <% if authenticated? %>
    <%= form_tag session_path, method: :delete do  %>
      <%= submit_tag 'Logout' %>
    <% end %>
  <% end %>
  <ul>
    <li>
      <%= link_to 'Repository', FbConnect::Application.config.repository %>
    </li>
    <li>
      <small>&copy; <%= link_to 'nov matake', 'https://github.com/nov' %></small>
    </li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1><%= link_to FbConnect::Application.config.title, root_path %></h1>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FB Connect Sample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<%= content_tag :body, class: controller_name do %>
    <%= render 'layouts/header' %>
    <div class="main">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  <% end %>
</html>

app/views/top/show.html.erb
<article>
  <nav class="connect">
    <%= link_to image_tag('facebook-connect-button.png'), authorize_facebook_path %>
  </nav>
</article>